class Model{
  String name,revenue,imgURL,info;
  Model(this.name,this.revenue,this.imgURL,this.info);
}
final List<Model> listCompanies= [
  Model("Walmart","\$485.9 Bilion","https://s.financesonline.com/uploads/2018/03/Walmart-edited.jpg","Walmart Inc. is an American multinational retail corporation that operates a chain of hypermarkets, discount department stores, and grocery stores. Headquartered in Bentonville, Arkansas, the company was founded by Sam Walton in 1962 and incorporated on October 31, 1969."),
  Model("State Grid Corporation of China ","\$315.2 Bilion","https://s.financesonline.com/uploads/2018/03/State-Grid-Corporation-of-China-edited.jpg","The State Grid Corporation of China, commonly known as the State Grid, is the state-owned electric utility monopoly of China. It is the largest utility company in the world, and as of 2018, the world's second largest company overall by revenue."),
  Model("Sinopec Group","\$267.5 Bilion","https://s.financesonline.com/uploads/2018/03/Sinopec-Group-edited.jpg","China Petroleum & Chemical Corporation, or Sinopec, is a Chinese oil and gas enterprise based in Beijing, China. It is listed in Hong Kong and also trades in Shanghai and New York."),
  Model("China National Petroleum Corporation","\$262.6 Bilion","https://s.financesonline.com/uploads/2018/03/China-National-Petroleum-Corporation-edited.jpg","The China National Petroleum Corporation is a major national oil and gas corporation of China PR and one of the largest integrated energy groups in the world. Its headquarters are in Dongcheng District, Beijing. CNPC was ranked fourth in 2017 Fortune Global 500, a global ranking of the largest corporations by revenue."),
  Model("Toyota Motor","\$254.7 Bilion","https://s.financesonline.com/uploads/2018/03/Toyota-Motor-edited.jpg","Toyota Motor Corporation is a Japanese multinational automotive manufacturer headquartered in Toyota, Aichi, Japan. In 2017, Toyota's corporate structure consisted of 364,445 employees worldwide and, as of September 2018, was the sixth-largest company in the world by revenue."),
  Model("Volkswagen","\$240.3 Bilion","https://s.financesonline.com/uploads/2018/03/Volkswagen-edited.jpg","Volkswagen AG, known internationally as the Volkswagen Group, is a German multinational automotive manufacturing company headquartered in Wolfsburg, Lower Saxony, Germany and indirectly majority owned by the Austrian Porsche-Piëch family."),
  Model("Royal Dutch Shell","\$240 Bilion","https://s.financesonline.com/uploads/2018/03/Royal-Dutch-Shell-edited.jpg","Royal Dutch Shell plc, commonly known as Shell, is a British-Dutch oil and gas company headquartered in the Netherlands and incorporated in the United Kingdom. It is one of the six oil and gas \"supermajors\" and the fifth-largest company in the world measured by 2018 revenues."),
  Model("Berkshire Hathway","\$223.7 Bilion","https://s.yimg.com/ny/api/res/1.2/s3ukAUqMImRutdElCBwXZA--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/http://media.zenfs.com/en/homerun/feed_manager_auto_publish_494/c664b6eab0191d3fe76907e5ca3fe871","Berkshire Hathaway is a holding company for a multitude of businesses. It's run by chairman and CEO Warren Buffett. Berkshire Hathaway is headquartered in Omaha, Nebraska and was originally a company comprised of a group of textile milling plants."),
  Model("Apple Inc","\$215.6 Bilion","https://s.financesonline.com/uploads/2018/03/Apple-Inc-edited.jpg","Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, and online services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook."),
  Model("Exxon Mobil","\$205 Bilion","https://s.financesonline.com/uploads/2018/03/Exxon-Mobil-edited.jpg","Exxon Mobil Corporation, doing business as ExxonMobil, is an American multinational oil and gas corporation headquartered in Irving, Texas. It is the largest direct descendant of John D. Rockefeller's Standard Oil Company, and was formed on November 30, 1999 by the merger of Exxon and Mobil."),
];